# This workflow will install Python dependencies, and run autopep8 on files in the repo


name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      run: |
        sudo apt update -y; 
        sudo  apt upgrade -y; 
        sudo apt install software-properties-common -y; 
        sudo add-apt-repository ppa:deadsnakes/ppa -y ;
        sudo apt update -y ; sudo apt install python3.13 -y
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run pylint on python files and save trace in post_traces folder
      run: |
        pylint $(find . -name "*.py") > post_traces/pylint_trace.txt
        
