# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Radon

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      run: |
        sudo apt update -y; 
        sudo  apt upgrade -y; 
        sudo apt install software-properties-common -y; 
        sudo add-apt-repository ppa:deadsnakes/ppa -y ;
        sudo apt update -y ; sudo apt install python3.13 -y
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run radon on all files and save trace in post_traces folder
      run: |
        radon cc ./*.py -s > post_traces/radon_trace.txt 
        
        
        
